### ISSUE TITLE
Error: secret option required for sessions

### ISSUE THREAD

**Issue by rezinch** [alexandrosmagos/instagram_commenter_ui#3]
Im getting this code when i open the localhost:3000 page

Error: secret option required for sessions
    at session (C:\Users\rezin\instagram_commenter_ui\node_modules\express-session\index.js:204:12)
    at Layer.handle [as handle_request] (C:\Users\rezin\instagram_commenter_ui\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\rezin\instagram_commenter_ui\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\rezin\instagram_commenter_ui\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\rezin\instagram_commenter_ui\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\rezin\instagram_commenter_ui\node_modules\express\lib\router\index.js:280:10)
    at urlencodedParser (C:\Users\rezin\instagram_commenter_ui\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (C:\Users\rezin\instagram_commenter_ui\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\rezin\instagram_commenter_ui\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\rezin\instagram_commenter_ui\node_modules\express\lib\router\index.js:286:9

**Comment by Skayzzz** [comment]
same issue here

**Comment by alexandrosmagos** [comment]
Have you renamed the .env example file to .env, and changed the session_secret string? And if so, make sure the `session_secret=''` exists

**Comment by Skayzzz** [comment]
Hi alex, my bad I forgot to answer. I did what the readme says and it's good now ! Thank you so much for the code

**Comment by nicobenegass** [comment]
Happened to me before, even changing the string. I found out that i didn't clone the repository right, somehow this being my first time i downloaded the zip of the code and runned it directly from there. 
Then i downgraded the node version just in case, and cloned the repository the right way (from cmd) and all went good! 

PS: made an account just to comment this
